### ISSUE TITLE
获取CK报错

### ISSUE THREAD

**Issue by ytgo** [GOOD-AN/Mys-Exchange-Goods#18]
请在浏览器打开https://user.mihoyo.com/#/login/captcha, 输入手机号后获取验证码, 但不要登录, 然后在下方按提示输入数据。
运行出错, 错误为: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error , 错误行数为: 25
按回车键继续

**Comment by GOOD-AN** [comment]
你是什么系统？可以先把25行和66行注释掉，这是单纯将网址复制到剪切板的命令

**Comment by ytgo** [comment]
debian 10 Python 3.9.2

**Comment by GOOD-AN** [comment]
你看下它给的网址 https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error ，对Linux上有解释

**Comment by ytgo** [comment]
谢谢
